---
- name: 사용자 정의 팩트배포
  hosts: web1
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks:
  # 1) etc/ansible/facts.d : 디렉토리생성
  # 2) 팩트파일 배포 (files/custom.fact)
    - name:
      file: 
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'
    
    - name:
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
        