---
- name: Virtual Hosting Role
  hosts: webservers

  pre_tasks:
    - name: pre_tasks messages
      debug:
        msg:  ===== START =====
  roles:
    - myvhost
  
  post_tasks:
    - name:
      debug:
        msg:  ==== STOP =====