---
- name: Deploy and start Apache httpd Service
  hosts: webserver
  tasks:
    # 1) 패키지 설치 - httpd, mod_ssl, python3-PyMySQL, firewalld
    # 2) 서비스 설정 - /var/www/html/index.html
    # 3) 서비스 실행 - httpd, firewalld
    # 4) 방화벽 등록 - http, https
    - name:
      yum:
        name:
          - httpd
          - mod_ssl
          - python3-PyMySQL
          - firewalld
        state: latest
    
    - name:
      copy:
        content: "Please Study hardly"
        dest: /var/www/html/index.html
        owner: ansible
        group: ansible
        mode: '755'

    - name:
      service:
        name: "{{ item }}"
        state: started
        enabled: yes  
      loop:
        - httpd
        - firewalld
    - name:
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https



  