---
- name: Restore
  hosts: webserver
  tasks:
    # 1) 방화벽 제거 
    # 2) 서비스 실행제거
    # 3) 서비스 설정파일 제거
    # 4) 패키지 삭제 
    - name: 방화벽 제거 
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - http
        - https
      ignore_errors: yes

    - name: 서비스 실행 제거 
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - httpd
        - firewalld
      ignore_errors: yes

    - name: 서비스 설정파일 제거 
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: 패키지 삭제 
      yum:
        name:
          - httpd
          - mod_ssl
          - python3-PyMySQL
          - firewalld
        state: absent

