---
- name: Configure
  hosts: all
  vars:
    system_owner: webmaster@exmaple.com
  gather_facts: yes
  tasks:
    - name: Deploy /etc/motd file
      template:
        src: template/motd.j2
        dest: /etc/motd
        
